### ISSUE TITLE
`this.path()` not working in VSCode with radian console 

### ISSUE THREAD

**Issue by ArielGC** [ArcadeAntics/this.path#10] opened 2023-03-13 15:02 UTC
Hi,
I'm currently running R (4.2.0) from VScode 1.76.0 in Windows through the its R extension and using the Radian console (https://github.com/randy3k/radian). But when I try to use the functions of this.path package I get the following error:

![image](https://user-images.githubusercontent.com/63074428/224740849-7660b20a-2ec7-42ae-8472-4dada47b233f.png)

How can I fix it?

**Comment by ArcadeAntics** [comment] 2023-03-15 09:27
Hai! Yes, I tried doing the same and I got an error as well.

To determine if we are in VSCode, I had something like this:

```R
gui.vscode <- interactive() && isTRUE(Sys.getenv("TERM_PROGRAM") == "vscode") && maybe.in.shell
```

where `maybe.in.shell` is another variable that is far too long and confusing to paste here, but it is TRUE or FALSE dependent on the values of `.Platform` and `commandArgs()`. You can see its full definition here:

https://github.com/ArcadeAntics/this.path/blob/main/R/promises.R#L235

The problem is that `maybe.in.shell` is `FALSE` with the radian console since `commandArgs()[[1L]]` is `"radian"` and not the usual `"Rterm.exe"`. So **this.path** thinks we are not in VSCode even though we are. I made a small change to `gui.vscode`, it now looks something like:

```R
gui.vscode <- interactive() && isTRUE(Sys.getenv("TERM_PROGRAM") == "vscode") && (maybe.in.shell || commandArgs()[[1L]] == "radian")
```

which should now be TRUE when using the radian console in VSCode.

In the next hour or so, I should have this committed and a tarball and the binaries available. When the update is available, you can install it with:

```R
install.packages("this.path", repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```

and then please confirm whether this fixes your issue. Thank you!

**Comment by ArielGC** [comment] 2023-03-15 13:57
It worked. Now I can use this.path inside radian console without errors.
Thanks a lot !

**Comment by ArcadeAntics** [comment] 2023-03-16 04:24
Awesome, glad it works! And thank you for pointing out this bug. Have a nice day!

**Closed as completed by ArcadeAntics** 2023-03-16 04:24 UTC
Labels: bug
